require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ThreadPartsController do

  # This should return the minimal set of attributes required to create a valid
  # ThreadPart. As you add validations to ThreadPart, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all thread_parts as @thread_parts" do
      thread_part = ThreadPart.create! valid_attributes
      get :index
      assigns(:thread_parts).should eq([thread_part])
    end
  end

  describe "GET show" do
    it "assigns the requested thread_part as @thread_part" do
      thread_part = ThreadPart.create! valid_attributes
      get :show, :id => thread_part.id
      assigns(:thread_part).should eq(thread_part)
    end
  end

  describe "GET new" do
    it "assigns a new thread_part as @thread_part" do
      get :new
      assigns(:thread_part).should be_a_new(ThreadPart)
    end
  end

  describe "GET edit" do
    it "assigns the requested thread_part as @thread_part" do
      thread_part = ThreadPart.create! valid_attributes
      get :edit, :id => thread_part.id
      assigns(:thread_part).should eq(thread_part)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ThreadPart" do
        expect {
          post :create, :thread_part => valid_attributes
        }.to change(ThreadPart, :count).by(1)
      end

      it "assigns a newly created thread_part as @thread_part" do
        post :create, :thread_part => valid_attributes
        assigns(:thread_part).should be_a(ThreadPart)
        assigns(:thread_part).should be_persisted
      end

      it "redirects to the created thread_part" do
        post :create, :thread_part => valid_attributes
        response.should redirect_to(ThreadPart.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved thread_part as @thread_part" do
        # Trigger the behavior that occurs when invalid params are submitted
        ThreadPart.any_instance.stub(:save).and_return(false)
        post :create, :thread_part => {}
        assigns(:thread_part).should be_a_new(ThreadPart)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ThreadPart.any_instance.stub(:save).and_return(false)
        post :create, :thread_part => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested thread_part" do
        thread_part = ThreadPart.create! valid_attributes
        # Assuming there are no other thread_parts in the database, this
        # specifies that the ThreadPart created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ThreadPart.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => thread_part.id, :thread_part => {'these' => 'params'}
      end

      it "assigns the requested thread_part as @thread_part" do
        thread_part = ThreadPart.create! valid_attributes
        put :update, :id => thread_part.id, :thread_part => valid_attributes
        assigns(:thread_part).should eq(thread_part)
      end

      it "redirects to the thread_part" do
        thread_part = ThreadPart.create! valid_attributes
        put :update, :id => thread_part.id, :thread_part => valid_attributes
        response.should redirect_to(thread_part)
      end
    end

    describe "with invalid params" do
      it "assigns the thread_part as @thread_part" do
        thread_part = ThreadPart.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ThreadPart.any_instance.stub(:save).and_return(false)
        put :update, :id => thread_part.id, :thread_part => {}
        assigns(:thread_part).should eq(thread_part)
      end

      it "re-renders the 'edit' template" do
        thread_part = ThreadPart.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ThreadPart.any_instance.stub(:save).and_return(false)
        put :update, :id => thread_part.id, :thread_part => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested thread_part" do
      thread_part = ThreadPart.create! valid_attributes
      expect {
        delete :destroy, :id => thread_part.id
      }.to change(ThreadPart, :count).by(-1)
    end

    it "redirects to the thread_parts list" do
      thread_part = ThreadPart.create! valid_attributes
      delete :destroy, :id => thread_part.id
      response.should redirect_to(thread_parts_url)
    end
  end

end
